appname = openagent
httpport = 14000
runmode = dev
SessionOn = true
copyrequestbody = true
driverName = mysql
dataSourceName = root:123456@tcp(localhost:3306)/
dbName = casibase
redisEndpoint =
guacamoleEndpoint = 127.0.0.1:4822
isDemoMode = false
logPostOnly = true
landingFolder =
casdoorEndpoint =
clientId =
clientSecret =
casdoorOrganization =
casdoorApplication =
redirectPath = /callback
cacheDir = "C:/casibase_cache"
appDir = ""
isLocalIpDb = false
audioStorageProvider = ""
providerDbName = ""
socks5Proxy = "127.0.0.1:10808"
publicDomain = ""
adminDomain = ""
enableExtraPages = false
shortcutPageItems = []
usageEndpoints = []
iframeUrl = ""
forceLanguage = ""
defaultLanguage = "en"
staticBaseUrl = "https://cdn.openagentai.org"
htmlTitle = "OpenAgent"
faviconUrl = "https://cdn.casibase.com/static/favicon.png"
logoUrl = "https://cdn.openagentai.org/img/openagent-logo_1600x276.png"
navbarHtml = ""
footerHtml = "Powered by <a target="_blank" href="https://github.com/the-open-agent/openagent" rel="noreferrer"><img style="padding-bottom: 3px;" height="20" alt="OpenAgent" src="https://cdn.openagentai.org/img/openagent-logo_1600x276.png" /></a>"
appUrl = ""
frontendBaseDir = "../openagent"
showGithubCorner = false
defaultThemeType = "default"
defaultColorPrimary = "#404040"
defaultBorderRadius = 10
defaultIsCompact = false
avatarErrorUrl = "https://cdn.openagentai.org/gravatar/error.png"
logConfig = {"adapter":"file", "filename": "logs/openagent.log", "maxdays":99999, "perm":"0770"}
